Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: agcs-lab4-bucketba
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0d06583a13678c938
      SubnetId: subnet-07fceddf94a208a0a
